# -*- coding: utf-8 -*-
"""CIE4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FpFNAfu9Pfoz2X-eVh2S-aUW8rsArKgV
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
data=pd.read_csv('/content/Mall_Customers.csv')
data

data.head()

data.describe()

data.info()

data.isnull().sum()

x=data.iloc[:,[3,4]].values

wcss_list=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(x)
  wcss_list.append(kmeans.inertia_)
plt.plot(range(1,11),wcss_list)
plt.title('elbow method')
plt.xlabel('number of clusters')
plt.ylabel('wcss_list')
plt.show()

optimal_clusters=5
Kmeans=KMeans(n_clusters=5,init='k-means++',random_state=42)
y_predict=kmeans.fit_predict(x)
y_predict

plt.scatter(x[y_predict==0,0],x[y_predict==0,1],s=100,c='red',label='cluster1')
plt.scatter(x[y_predict==1,0],x[y_predict==1,1],s=100,c='blue',label='cluster2')
plt.scatter(x[y_predict==2,0],x[y_predict==2,1],s=100,c='green',label='cluster3')
plt.scatter(x[y_predict==3,0],x[y_predict==3,1],s=100,c='cyan',label='cluster4')
plt.scatter(x[y_predict==4,0],x[y_predict==4,1],s=100,c='magenta',label='cluster5')
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=300,c='yellow',label='centroid')
plt.title('cluster of clients')
plt.xlabel('annual income')
plt.ylabel('spending score')
plt.legend()
plt.show()